### ISSUE TITLE
normalise "C:\\\\" on Windows

### ISSUE THREAD

**Issue by mvoidex** [haskell/filepath#71] opened 2018-10-10 13:38 UTC
Shouldn't it be equal `C:\\`?

**Comment by ndmitchell** [comment] 2018-10-12 14:49
Yes, probably. Going to close as a dupe of https://github.com/haskell/filepath/issues/12#issuecomment-284206275, which suggests a significant normalise rewrite.

**Closed by ndmitchell** 2018-10-12 14:49 UTC
