### ISSUE TITLE
API redesign proposal

### ISSUE THREAD

**Issue by BurningWitness** [haskell/filepath#237] opened 2024-10-15 14:48 UTC
> [!NOTE]    
> This all spun off of [this](https://discourse.haskell.org/t/if-ospath-is-intended-to-replace-filepath-why-isnt-filepath-deprecated/10405/18) Discourse thread, but reading that thread is not necessary to get through this issue.

## Preamble

I made a command-line options parser a while ago and I tried to use the new `OsString`/`OsPath` API to upgrade it from the clearly inefficient legacy `FilePath` format. I find the current API structure to be both confusing for high-level use and insufficient for anything more complex than high-level use.

It is my belief that both of these problems can be remedied within the scope of this library without compromising on any of its goals.

The following concerns and the proposed changes apply only to decoding and encoding in `os-string` and all boot libraries that rely on its types. `xxcode` refers to `encode` and `decode` together.

## Concerns

<details>
  <summary>1</summary>
  
  ### `PosixPath ~ PosixString` is incoherent
  
  Reasoning:

  1. A `PosixString`, by its [current definition](https://hackage.haskell.org/package/os-string-2.0.6/docs/System-OsString-Posix.html), is a sequence of raw bytes of no particular encoding.

  2. For `PosixPath` the API provides two kinds of functionality:

      a. `PosixPath` can be encoded with the encoding of one's choice (API [heavily leans towards UTF-8](https://hackage.haskell.org/package/filepath-1.5.3.0/docs/System-OsPath-Posix.html#v:pstr));
      
      b. `PosixPath` supports a set of modifying operations that refer to characters `'.'` and `'/'`.

  5. If `PosixPath ~ PosixString`, then point 2 may no longer apply fully because it clashes with point 1. The only way this would make sense is if `PosixPath` were instead a black box: one would be able to encode a string into it (2a), but would not be able to talk about the encoding from that point on (not 2b).

  6. However, since the library chooses to keep point 2 in full, an assumption on the implementation of 2b must be made and that assumption currently is that the encoding is single-byte. For the purposes of the filepath package this is compatible with UTF-8, since UTF-8 is self-synchronizing and filepath only cares about character lookup.
  
  Problems that arise from this:

  1. Most functions from `System.OsString.Posix` are unsafe to use with `PosixPath`s, but the types do not reflect that:

      ```haskell
      > let path = [System.OsPath.Posix.pstr|/tmp/𝗔𝗕𝗖.def|] :: PosixPath
      > System.OsString.Posix.dropEnd 8 path :: PosixPath
      "/tmp/\240\157\151\148\240\157\151\149"
      ```

  2. Any function that encodes a `PosixPath` with a variable-width encoding is only safe in terms of the `filepath` API when no successive bytes in said encoding can be `0x2E` and `0x2F` (ASCII `'.'` and `'/'` respectively) .

3. `IsString PosixPath` morally could exist and would be in UTF-8, but cannot be a part of the API because that would result in IsString `PosixString`.

4. All of this is confusing to library users and should be extensively documented.

Benefits over keeping this instead of fixing it:

1. `PosixPath` can be created in any encoding (as long as the aforementioned successive bytes rule is not broken) and allows mixing arbitrary encodings at will;

2. Good enough for the overwhelming majority of real-world uses regardless of the issues solely due to a confluence of historical reasons.

---

### Proposed remedy

Steps:

1. Restrict the `PosixPath` definition to a single coherent encoding.
   
    UTF-8-with-surrogates appears to be the best choice for this: UTF-8 allows for no-copy `ShortText` conversions, it is the most widely used encoding and the roundtripping algorithm GHC provides supports it.

2. Alter `type PlatformPath = OsString`.

    All references to `PlatformPath` can now be deprecated.
    
3. Apply the changes to the POSIX-specific part of the API.

    Note that addressing this concern in isolation would not yield much of a benefit type-wise:
    
    ```haskell
    -- FilePath and PosixPath are both UTF-8, so a (FilePath -> PosixPath) conversion could be a no-op
    -- if we chose our types better. This is however beyond the scope of this concern.
    decodeUtf :: MonadThrow m => PosixString -> m String
    
    -- `PosixPath` can now be used to hold the roundtripped file path without checking for its correctness immediately.
    -- This function can thus be decoupled. The type change is however beyond the scope of this concern.
    decodeFS :: PosixString -> IO String
    ```

Benefits:

1. Fixes all aforementioned encoding problems.

2. `PosixPath` is now symmetric with `WindowsPath`, so `OsPath` can be uniformly described as a "potentially ill-formed file path" type.

     From the user perspective this is clearly distinguishable from `OsString` (the "raw system file path") and `FilePath` (the "well-formed file path").

     Additionally `Show OsPath` can now be uniform between the two platform types and `IsString OsPath` can be defined unambiguously.

Downsides:

1. Discriminates against all other encodings.

   Anyone wishing to use `filepath` functionality with a different encoding will be forced to either suffer conversion overheads or to handroll their own functions.
   
---

</details>

<details>
  <summary>2</summary>
  
  ### Platform-specific APIs should be explicit with format conversions
  
  As it currently stands platform-specific encoding APIs are defined with the expectation that `FilePath = String` and API functions are not properly broken down beyond that point.

  This is fine for the most basic of use cases, however for anything more fine-grained it introduces unnecessary overhead. For example, if we have a `Text` and we wish to convert that to a UTF-8 `PosixPath`, the safe API gives us no other choice but to go through `Text --> String --> PosixPath`, which involves an unnecessary double `String` conversion.

---

### Proposed remedy

Steps:

1. Define `ShortUTF8` and `ShortUTF16LE` in Posix and Windows APIs respectively. These are newtyped `ShortByteString`s that hold their respective encodings. Their constructors are unsafe.

2. Define convenience functions for converting between these two types and `String`. The convenience functions should only be exposed in the modules for relevant platforms.

3. Restructure functions in platform-specific APIs to return these types instead of `FilePath`s.

    For Windows specifically an additional set of conversions between `WindowsString` and `ShortUTF8` can be provided, as it minimizes the number of conversions for the common user cases.

    Note that while addressing this concern in isolation is fine, it is more effective when combined with other changes:

    ```haskell
    -- PosixString and ShortUTF8 have the same internal representation, so this function can now be performed
    -- without extra allocations.
    decodeUtf8 :: MonadThrow m => PosixString -> m ShortUTF8
    
    -- If PosixPath were to have an encoding compatible with ShortUTF8, then a (ShortUTF8 -> PosixPath) conversion
    -- would be a type-safe no-op. Altering PosixPath is however beyond the scope of this concern.
    decodePath :: MonadThrow m => PosixPath -> m ShortUTF8
    ```

4. (future) Should GHC ever introduce a boot library that handles either of these encodings, this package's definitions can be deprecated with minimal hassle in favor of that library's.

There are no user-facing downsides to this in my view: the library already performs these operations internally and type safety is preserved.

---
  
</details>

<details>
  <summary>3</summary>
  
  ### Best guess on Windows is not the same as best guess on Unix
  
  Under Unix raw file paths come with no encoding expectations. Applications make guesses based on the passed locale. UTF-8 is a good guess because it's the most commonly used encoding, but any application running on a non-UTF-8 system that assumes UTF-8 will only correctly interpret a small subset of characters (generally ASCII).

  Under Windows raw file paths are known to be in UCS-2. Applications are expected to use UTF-16LE[<sup>[per Microsoft]</sup>](https://learn.microsoft.com/en-us/windows/win32/intl/unicode), which makes it the best guess and every other possible encoding can be safely ignored as long as well-formedness checks are performed.

  This library already agrees that the two are different [internally](https://github.com/haskell/os-string/blob/06a9edc5d25191f658407786d9d964e34d09755f/System/OsString/Encoding/Internal.hs#L262-L274), however it attempts to present the two as equal type-wise on the outside.
  
  The result is that platform-specific APIs do not talk about platform specifics when it comes to encodings, rendering them rather pointless for applications that wish to decide based on these specifics.

  ---

  ### Proposed remedy  

  Steps:

  1. Restrict the signatures in the Windows-specific API and decouple the ones in the Posix-specific API.
  
      Note that the impact of addressing this in isolation is negligible, as meaningful changes require intermediate types that this library does not currently provide:

      ```haskell
      -- No longer requires IO
      decodeFS :: WindowsString -> Either EncodingException String
    
      -- This function is a locale lookup plus roundtripping encoding plus a String conversion.
      -- Altering the definition of PosixPath and introducing ShortUTF8 are both beyond the scope of this concern however.
      decodeFS :: MonadThrow m => PosixString -> m String
      ```

  There are no user-facing downsides to this in my view: the library already performs these operations internally and type safety is preserved.

  ---
  
</details>

## Proposed solution

Proposed library user experience:

- All system commands now only accept `OsString`s. This means all of `file-io` needs to be reframed in terms of `OsString`.

- Platform-specific APIs no longer duplicate the platform-independent API in functionality. Using a platform-specific API may allow for more efficient alternative function definitions for that particular platform.

- If the library user wishes to convert an `OsString` into an `OsPath`, they now have to explicitly choose the conversion method (`decodeUtf`, `decodeFS`, `decodeLE`). Conversion methods may fail and are not guaranteed to produce well-formed text;

- If the library user wishes to safely use an `OsPath` as text, they have to check it for correctness and convert it to the encoding of their choice. Currently this is assumed to be `String`, for legacy reasons, but this library can add support any UTF-8 byte array type, provided it can depend on the package exposing it.

- Converting proper text (such as `String`) into `OsPath` is lossless and never fails.

- Converting from `OsPath` to `OsString` once again requires a deliberation on library user's side. Similar to the decoding counterpart, this may fail and is not guaranteed to result in raw file paths that are well-formed from the platform's perspective.

Steps are a combination of all steps to remedy aforementioned concerns, plus:
  
- (optional) Sanitation functions. 

---

<details>
  <summary>List of changes</summary>
  
  <br>
  
  ### Posix-specific API changes
  
  `PosixPath` now represents a potentially-ill-formed UTF8 file path.
  
  `decodeUtf` is broken down into `decodeUtf8 --> packUtf8`.
  
  `encodeUtf`.is broken down into `unpackUtf8 --> encodePath --> encodeUtf8`.
  
  `decodeWith` is broken down into `decodeWith --> packUtf8`.
  
  `encodeWith`.is broken down into `unpackUtf8 --> encodePath --> encodeWith`.
  
  `decodeLE` is broken down into `getLocaleEncoding --> decodeWith --> packUtf8`.
  
  `encodeLE`.is broken down into `getLocaleEncoding --> unpackUtf8 --> encodePath --> encodeWith`.
  
  `decodeLE` is broken down into `getFileSystemEncoding --> unsafeDecodeWith --> decodePath --> packUtf8`.
  
  `encodeLE`.is broken down into `getFileSystemEncoding --> unpackUtf8 --> encodePath --> unsafeEncodeWith`.
  
  ```haskell
  {- support -}
    
  -- Well-formed UTF-8. Constructor is unsafe.
  newtype ShortUTF8 = ShortUTF8 ShortByteString

  packUtf8 :: ShortUTF8 -> FilePath

  unpackUtf8 :: FilePath -> ShortUTF8


  -- Potentially ill-formed UTF-8. Constructor is unsafe.
  newtype PosixPath = PosixPath ShortByteString
  
  -- packUtf8, possibly sanitized.
  instance Show PosixPath
  
  -- (encodePath . unpackUtf8)
  instance IsString PosixPath
    
    
  {- encode -}

  -- No-op
  encodePath :: ShortUTF8 -> PosixPath

  -- No-op
  encodeUtf8 :: PosixPath -> PosixString

  -- Uses GHC.IO.Encoding to encode from UTF-8 to a char array and then to the wanted encoding.
  encodeWith :: TextEncoding -> PosixPath -> IO (Either EncodingException PosixString)

  -- Encoding must roundtrip and be UTF-8-compatible. getFileSystemEncoding satisfies these criteria.
  unsafeEncodeWith :: TextEncoding -> PosixPath -> IO PosixString


  {- decode -}
  -- Convenience function for replacing all invalid surrogates with '�'.
  sanitizePath :: PosixPath -> ShortUTF8

  -- No-copy UTF-8 well-formedness check
  decodePath :: PosixPath -> Either Error ShortUTF8

  -- No-copy UTF-8 well-formedness check, same as 'decodePath'
  decodeUtf8 :: PosixString -> Either Error ShortUTF8

  -- Uses GHC.IO.Encoding to decode from the wanted encoding to a char array and then to UTF8.
  decodeWith :: TextEncoding -> PosixString -> IO (Either EncodingException ShortUTF8)

  -- Encoding must roundtrip and be UTF-8-compatible. getFileSystemEncoding satisfies these criteria.
  unsafeDecodeWith :: TextEncoding -> PosixString -> IO PosixPath
  ```
  
  ### Windows-specific API changes
  
  `decodeUtf` is broken down into `decodeUtf16le --> packUtf16le`.
  
  `encodeUtf` is broken down into `unpackUtf16le --> encode16le`.
  
  `decodeWith` is broken down into `unsafeDecodeWith --> packUtf16le`.
  
  `encodeWith` is broken down into `unpackUtf16le --> unsafeEncodeWith`.
  
  `xxcodeLE` functions dissolve, as encoding is known to be UTF-16 and `xxcodeUtf` functions provide that.
  
  `xxcodeFS` functions are duplicates of `xxcodeLE`.
  
  ```haskell
  {- support -}
  
  -- | Well-formed UTF-16LE. Constructor is unsafe.
  newtype ShortUTF16LE = ShortUTF16LE ShortByteString
  
  packUtf16le :: ShortUTF16LE -> FilePath
  
  unpackUtf16le :: FilePath -> ShortUTF16LE
  
  utf8ToUtf16le :: ShortUTF8 -> ShortUTF16LE
  
  utf16leToUtf8 :: ShortUTF16LE -> ShortUTF8
  
  
  {- encode -}
  
  -- No-op
  encodeUtf16le :: ShortUTF16LE -> WindowsString
  
  -- Uses GHC.IO.Encoding to encode from UTF-16LE to a char array and then to the wanted encoding.
  -- Encoding must be two-byte.
  unsafeEncodeWith :: TextEncoding -> ShortUTF16LE -> IO (Either EncodingException WindowsString)

  
  {- decode -}
  
  -- Convenience function for replacing all invalid surrogates with '�'. May be used for 'Show'.
  sanitizePath :: WindowsPath -> ShortUTF16LE
  
  -- No-copy UTF-16LE well-formedness check
  decodeUtf16le :: WindowsString -> Either EncodingException ShortUTF16LE
  
  -- Uses GHC.IO.Encoding to decode from wanted encoding to a char array and then to UTF-16LE.
  -- Encoding must be two-byte.
  unsafeDecodeWith :: TextEncoding -> WindowsString -> IO (Either EncodingException ShortUTF16LE)
  ```

  ### Platform-independent API changes</summary>

  `OsPath` now represents a potentially-ill-formed Unicode file path.

  `xxcodeWith` functions should be excluded from this API as per Concern 3.
  
  `xxcodePath` has been split off of the rest of the functions as conversions between `OsPath` and  `FilePath`. Any library that wishes to use a `FilePath` type other than `String` now only needs to replace these two functions.

  `xxcodeUtf`, `xxcodeFS` and `xxcodeLE` now convert into `OsPath`s, not `FilePath`s. 

  `xxcodeUtf` functions are now no-ops. All the downsides of Concern 1 now only apply when processing Posix paths using these functions.
  
  `xxcodeFS` can now be used without correctness checks.
  
  `decodeLE` when combined with `decodePath` now results in an unnecessary UTF-8 well-formedness check on Unix. This can still be bypassed by using platform-specific APIs, so it shouldn't be an issue.
  
  *The following is proof that the types are strong enough to wire everything up correctly, not strictly proper Haskell code.*
  
  ```haskell
  
  {- support -}
  type PlatformPath = OsString
  
  
  newtype OsPath @Windows = WindowsPath
  newtype OsPath @Posix   = PosixPath
  
  instance Show OsPath where
    showsPrec i @_ = showsPrec i
  
  instance IsString OsPath where
    fromString @_ = fromString
  
  
  {- encode -}
  
  encodePath :: FilePath -> OsPath
  encodePath @Windows = Windows.encodeUtf16le . Windows.unpackUtf16le
  encodePath @Posix   = Posix.encodePath . Posix.unpackUtf8
  
  encodeUtf :: OsPath -> OsString
  encodeUtf @Windows = id
  encodeUtf @Posix   = Posix.encodeUtf8
  
  encodeFS :: OsPath -> IO OsString
  encodeFS @Windows = pure
  encodeFS @Posix   = \path -> do
    locale <- GHC.IO.Encoding.getFileSystemEncoding
    Posix.unsafeEncodeWith locale path
    
  -- right now resides in os-string, but probably should be in filepath.
  encodeLE :: OsPath -> IO OsString
  encodeLE @Windows = pure
  encodeLE @Posix   = \path -> do
    locale <- GHC.IO.Encoding.getLocaleEncoding
    either throw pure $ Posix.encodeWith locale path
  
  
  {- decode -}
  
  -- Convenience function for replacing all invalid surrogates with '�'
  sanitizePath :: OsPath -> FilePath
  sanitizePath @Windows = Windows.packUtf16le . Windows.sanitizePath
  sanitizePath @Posix   = Posix.packUtf8 . Posix.sanitizePath
  
  decodePath :: MonadThrow m => OsPath -> m FilePath
  decodePath @Windows = either throw (pure . Windows.unpackUtf16le) . Windows.decodeUtf16le
  decodePath @Posix   = either throw (pure . Posix.packUtf8) . Posix.decodePath
  
  decodeUtf :: OsString -> OsPath
  decodeUtf @_ = id
  
  decodeFS :: OsString -> IO OsPath
  decodeFS @Windows = pure
  decodeFS @Posix   = \string -> do
    locale <- GHC.IO.Encoding getFileSystemEncoding
    Posix.unsafeDecodeWith locale string
    
  -- right now resides in os-string, but probably should be in filepath.
  decodeLE :: OsString -> IO OsPath
  decodeLE @Windows = pure
  decodeLE @Posix   = \path -> do
    locale <- GHC.IO.Encoding.getLocaleEncoding
    either throw (pure . Posix.packUtf8) $ Posix.decodeWith locale path
  ```
  
</details>

**Comment by hasufell** [comment] 2024-10-16 03:28
> If PosixPath ~ PosixString, then point 2 may no longer apply fully because it clashes with point 1. The only way this would make sense is if PosixPath were instead a black box: one would be able to encode a string into it (2a), but would not be able to talk about the encoding from that point on (not 2b).

I can't follow this reasoning.

What exactly is the problem with encoding arbitrary strings into a `PosixPath`? The only restriction `PosixPath` has over `PosixString` is that `NUL` bytes are "not allowed" (they actually are, but the system calls will truncate your string). See

https://github.com/haskell/filepath/blob/e794e7376755fdaecae6fc23bd34556d46c46307/System/FilePath/Internal.hs#L1114-L1126

The system calls don't care what the encoding is. They will scan for the `/` byte as is defined by the posix standard.

If you want to attach encoding information to the type, create a tuple or a newtype wrapper.

> However, since the library chooses to keep point 2 in full, an assumption on the implementation of 2b must be made and that assumption currently is that the encoding is single-byte. For the purposes of the filepath package this is compatible with UTF-8, since UTF-8 is self-synchronizing and filepath only cares about character lookup.

This is wrong.

It is not an assumption of the encoding. Please understand the system calls and the operating system API.

On unix, a filepath is defined as `char*`, so the smallest unit of a filepath is a `char` (1 byte). This is all that matters to the operating system API:

* https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_170
* https://pubs.opengroup.org/onlinepubs/007904875/functions/open.html

Likewise on windows, filepaths are `wchar_t*`, which is a **wide char array** (2 bytes). You *can't* pass a `char` to the operating system API:

* https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew
* https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/76f10dd8-699d-45e6-a53c-5aefc586da20

Since you can theoretically have all sorts of different multibyte encodings stuffed into filepaths on any platform (so as long as they don't accidentally encode as the path separator), there is no way to treat a filename (as opposed to filepath) correctly, unless you **know the encoding**.

This is the entire point of the new API: **we don't know the damn encoding**, but we don't have to for dealing with filepaths (and finding path separators).

> Restrict the PosixPath definition to a single coherent encoding.
> 
> UTF-8-with-surrogates appears to be the best choice for this: UTF-8 allows for no-copy ShortText conversions, it is the most widely used encoding and the roundtripping algorithm GHC provides supports it.

This goes against the philosophy of the new API. We don't make assumptions over the encodings. Using UTF-8b is a random decision and makes people stop thinking about corner cases, which is why most Haskell applications handle filepaths incorrectly.

If you want to have an API that works in 80% of the cases, you can just stick to the old `FilePath ~ String` API. It makes exactly that trade-off.

> Discriminates against all other encodings

Exactly. The point of the new API is to stop that discrimination.

----

> This is fine for the most basic of use cases, however for anything more fine-grained it introduces unnecessary overhead. For example, if we have a Text and we wish to convert that to a UTF-8 PosixPath, the safe API gives us no other choice but to go through Text --> String --> PosixPath, which involves an unnecessary double String conversion.

filepaths are short and have a maximum length. Do you have proof that this is an actual problem?

I don't think I will add more types to this library, but a `reEncode :: PosixString -> TextEncoding -> PosixString` function could very well be provided.

The functions and types you want can easily be implemented outside of `filepath`.

----

> This library already agrees that the two are different [internally](https://github.com/haskell/os-string/blob/06a9edc5d25191f658407786d9d964e34d09755f/System/OsString/Encoding/Internal.hs#L262-L274), however it attempts to present the two as equal type-wise on the outside.
> 
> The result is that platform-specific APIs do not talk about platform specifics when it comes to encodings, rendering them rather pointless for applications that wish to decide based on these specifics.

Duplicate of:

* https://github.com/haskell/os-string/issues/6
* https://github.com/haskell/os-string/issues/15

**Comment by BurningWitness** [comment] 2024-10-16 11:09
> The system calls don't care what the encoding is. They will scan for the `/` byte as is defined by the posix standard.

Indeed I am overly pessimistic in my description of `PosixString`, there are certain well-defined operations for it stemming from the definition linked. Functions that operate over `PosixPaths`s based on slash characters should have `PosixString` counterparts, which are safe.

> This is the entire point of the new API: we don't know the damn encoding, but we don't have to for dealing with filepaths (and finding path separators).

Okay, so, if I'm reading it correctly, it seems like both the dot and the slash are, per [6.2. Character Encoding](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap06.html#tag_06_02): the byte values used to encode \<period\>, \<slash\>, \<newline\>, and \<carriage-return\> shall not occur as part of any other character in any locale.

I assume it means that encodings that use bytes `0x2E` and `0x2F` are not POSIX-compatible, and since these are the only two characters this API cares about my Concern 1 is invalid.

---

At the cost of appearing as a goalpost-mover, perhaps yet again, why even introduce `type OsPath = OsString` then?

My expectation was effectively that `PosixPath` is a free name and as such could be elevated to feature parity with `WindowsPath` for user convenience, but since every `OsPath` operation is effectively an `OsString` one then doing so would mean duplicating the entire `filepath` API just to have two extra instances and two extra functions on this one type.

---

> filepaths are short and have a maximum length. Do you have proof that this is an actual problem?

This is not a question of length or performance considerations, it's a question of performing the minimal necessary set of conversions to achieve a result. The library already does these things internally, it inevitably has to test them (even if only in combination with other operations) and it can expose them in a type-safe way.

You can indeed make the argument that this library should not have to define these conversions, and there should instead be a boot library for working with basic encodings. I agree, but a library like that does not currently exist, so for the time being all necessary overlapping functionality should be defined in this library and provided by it.

**Comment by BurningWitness** [comment] 2024-10-16 11:59
> Using UTF-8b is a random decision and makes people stop thinking about corner cases, which is why most Haskell applications handle filepaths incorrectly.

By "handle filepaths incorrectly" you mean they merely assume that paths they receive from high-level commands like `System.Directory.listDirectory` are always well-formed, correct?

I don't think having a potentially ill-formed Unicode type that rests between `OsString` and `FilePath` would compromise type safety in any way here, and it is quite useful in that you can attach both the instances and the roundtripping decoder to it. Users who want to use proper UTF-8 can skip this with a no-op conversion anyway, and for everyone who wants the old behavior safely the choice between converting that type to proper Unicode (safe) or coercing it (unsafe) should still be available.

**Comment by BurningWitness** [comment] 2024-10-19 12:12
Returning to Concern 1, it would seem like the definition of `PosixString` should then be revised to roughly "a sequence of bytes in an unknown encoding (or a mix of), within which characters `<NUL>`, `<period>`, `<slash>`, `<newline>` and `<carriage-return>` are guaranteed to be represented with single bytes, to be invariant across all supported locales and to not occur as part of any other character in any locale".

The `PosixString` API should then reflect that, providing `PosixChar`s for all five of those characters out of the box (since four of those codes could differ between POSIX-compliant platforms), and only including operations that split/create `PosixString`s on/using those characters. Breaking `PosixString`s on arbitrary indices should only be available as an unsafe operation, since it allows breaking well-formed code points into ill-formed byte sequences.

In a similar vein for the Windows half of the API, I don't know if calling `WindowsString` encoding UCS-2 is entirely correct, because it looks like the surrogate block was only defined once UCS-2 was obsoleted. While it should be always correct to split UCS-2 on two-byte boundaries, doing so with `WindowsString`s may again introduce ill-formed byte sequences where before there were none.

**Comment by hasufell** [comment] 2024-10-19 12:26
> The PosixString API should then reflect that, providing PosixChars for all five of those characters out of the box (since four of those codes could differ between POSIX-compliant platforms), and only including operations that split/create PosixStrings on/using those characters. Breaking PosixStrings on arbitrary indices should only be available as an unsafe operation, since it allows breaking well-formed code points into ill-formed byte sequences.

Huh? Did you mean `PosixPath`?

`PosixString` is fine.

The filepath API itself doesn't provide breaking on arbitrary `PosixChar`s: https://hackage.haskell.org/package/filepath-1.5.3.0/docs/System-OsPath-Posix.html

The only thing that could be done is to make it harder to use `PosixString` API for filepaths. But what for, really?

I asked many people back then whether `PosixPath` should be a newtype, but decided against it.

Splitting posixpaths on `Word8`, again, **is perfectly safe**. You don't lose information. Whether it makes semantically sense is a different question.

The ship for a newtype has sailed, imo. It would be another breaking change that I have very low appetite for.

Following your argument, even `decodeUtf` is unsafe, even if it doesn't fail... because the underlying encoding might have been something entirely different that just passed the UTF-8 decoder by accident. 

And here you're contradicting yourself, because you basically suggested to do exactly that: use UTF-8b regardless of actual encoding.

**Comment by tomjaguarpaw** [comment] 2024-10-19 12:26
(I'm following along vaguely, and just wanted to make the parenthetical remark that I'm astonished to learn that `<slash>` is not required to have the same byte encoding on every POSIX system.)

**Comment by hasufell** [comment] 2024-10-19 12:55
> (I'm following along vaguely, and just wanted to make the parenthetical remark that I'm astonished to learn that `<slash>` is not required to have the same byte encoding on every POSIX system.)

Well, the posix API only treats `0x2F` as filepath separator.

But yes, if a user were to input UTF-16 byte sequences on unix, the results might be surprising.

If you were to write a file manager for posix systems that should support arbitrary encodings for **filenames**, you'd somehow have to disallow any byte sequence that contains `0x2F` and then have a strategy how to assemble filepaths via the UI.

**Comment by BurningWitness** [comment] 2024-10-19 13:58
> Huh? Did you mean `PosixPath`?

`PosixPath` is `PosixString` right now, by definition. The choice to put functions related to `filepath` in `System.OsPath.Posix` instead of `System.OsString.Posix` (and then reexport) is in my eyes entirely arbitrary.

I don't think `newtype PosixPath = PosixPath PosixString` would change this dynamic in any way.

> Splitting posixpaths on `Word8`, again, is perfectly safe.

Splitting UTF-8 on raw bytes is perfectly safe too, but noone expects `text` to provide functions of that kind in its safe modules.

> Following your argument, even decodeUtf is unsafe, even if it doesn't fail... because the underlying encoding might have been something entirely different that just passed the UTF-8 decoder by accident.

Correct, but I don't think the two are precisely comparable. Pretty much noone would want to do raw byte operations over `PosixString`; `decodeUtf` on the other hand has valid uses, so merely documenting the drawbacks is enough.

> And here you're contradicting yourself, because you basically suggested to do exactly that: use UTF-8b regardless of actual encoding.

All I'm saying on that front is that there's design space between `PosixString` and `FilePath` for a type that most of the community would find useful. I like to call that type `PosixPath` (for symmetry with `WindowsPath`), but I'm not insisting on it.

> Well, the posix API only treats `0x2F` as filepath separator.

The [Chapter 6.1](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap06.html) of the spec only states those characters are invariant across all supported locales, so I assume that would mean that a platform *can* use byte sequences that don't align with ASCII. Chances for a schism like that at this point are almost zero, but it would be neat if the libraries reflected this.

**Comment by hasufell** [comment] 2024-10-19 14:10
> All I'm saying on that front is that there's design space between PosixString and FilePath for a type that most of the community would find useful.

Alright. 

So to be brief: `filepath` will not change its types.

The type you want **can be implemented on top of the provided primitives**.

I personally don't find it very useful, but you're free to create such a library.

**Closed** 2024-10-19 14:10 UTC
